Repository hashicorp/vault-helm, pull requests merged in 2020-05, with the labels that each got.

#165 Add support for priorityClassName
  templates/injector-deployment.yaml
  templates/server-statefulset.yaml
  test/unit/server-statefulset.bats
  values.yaml
Labels: chart, enhancement

#258 Add init containers
  templates/server-statefulset.yaml
  test/unit/server-statefulset.bats
  values.yaml
Labels: chart, enhancement

#308 Update readme with helm repo info
  README.md
Labels: docs, enhancement

#309 Update default values
  values.yaml
Labels: bug, chart

#310 Update ingress apiVersion in chart
  templates/server-ingress.yaml
Labels: chart, enhancement

#270 fix annotation bug. Use active service on ingress when ha
  templates/server-ingress.yaml
  test/unit/server-ingress.bats
Labels: bug, chart
