Repository hashicorp/vault-helm, pull requests merged in 2022-01, with the labels that each got.

#670 csi: ability to set priorityClassName for csi daemonset pods
  CHANGELOG.md
  templates/csi-daemonset.yaml
  test/unit/csi-daemonset.bats
  values.schema.json
  values.yaml
Labels: enhancement, csi

#672 Fixed a small typo
  values.yaml
Labels: docs

#679 add namespace support for openshift route
  CHANGELOG.md
  templates/server-route.yaml
Labels: bug, vault, openshift

#673 Add volumes and env vars to helm hook test pod
  CHANGELOG.md
  templates/tests/server-test.yaml
  test/unit/server-statefulset.bats
  test/unit/server-test.bats
Labels: enhancement, vault

#686 Tests on top of 396
  CHANGELOG.md
  templates/server-route.yaml
  test/unit/server-route.bats
  values.yaml
Labels: enhancement, vault, openshift
